name : Simple CI-improved
on:
 push:
  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: docker build
        run: docker build -t my-app .

      - name: run container
        run: docker run -d -p 8085:80 my-app

      - name: container ps
        run: docker ps -a
